### ISSUE TITLE
Should the action use Plugin slug or Text domain?

### ISSUE THREAD

**Issue by bahiirwa** [varunsridharan/action-wp-pot-generator#1]
**Describe the bug**
Thank you for this great tool. I enjoy it.

This is more of a question:

I have found that when adding the action, the `item_slug` is considered as the reference for the texts to add. However, WP uses the text-domain in this case, would be `domain` as per the code of the repo. Is this intentional?

**Comment by varunsridharan** [comment]
well of you failed to provide `domain` in that case `item_slug` will be used as `text-domain` this is done by `wp-cli` please do refer this documentation for more info

> https://developer.wordpress.org/cli/commands/i18n/make-pot/

<blockquote><img src="//s.w.org/favicon.ico?2" width="48" align="right"><div>WordPress Developer Resources</div><div><strong><a href="https://developer.wordpress.org/">wp i18n make-pot | WP-CLI Command | WordPress Developer Resources</a></strong></div><div>Scans PHP and JavaScript files for translatable strings, as well as theme stylesheets and plugin files if the source directory is detected…</div></blockquote>

**Comment by bahiirwa** [comment]
This cleared it for me. https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains 

Thanks again.
